//! Shared patterns for container provenance detection.

use std::sync::OnceLock;

use regex::bytes::Regex as ByteRegex;
use regex::Regex;

use crate::image::markers::{AI_META_HINTS, C2PA_MARKERS};

/// Frontmatter / meta keys that often carry AI provenance.
pub const AI_FRONTMATTER_KEYS: &[&str] = &[
    "generator",
    "ai",
    "ai_generated",
    "ai-generated",
    "claude",
    "anthropic",
    "openai",
    "gemini",
    "synthid",
    "c2pa",
    "content_credentials",
    "contentcredentials",
    "provenance",
    "digital_source_type",
    "digitalsourcetype",
    "created_with",
    "createdwith",
    "model",
    "llm",
];

const AI_META_NAME_PATTERN: &str = r"(?i)generator|ai[-_ ]?generated|claude|anthropic|openai|gemini|synthid|c2pa|content.?credential|provenance|digital.?source|aigc";

/// Names and values that read as AI provenance.
pub fn ai_meta_name_re() -> &'static Regex {
    static RE: OnceLock<Regex> = OnceLock::new();
    RE.get_or_init(|| Regex::new(AI_META_NAME_PATTERN).expect("static regex compiles"))
}

/// The byte-oriented twin, for the container paths that never decode.
pub fn ai_meta_name_re_bytes() -> &'static ByteRegex {
    static RE: OnceLock<ByteRegex> = OnceLock::new();
    // Byte semantics, as Python's `re` uses on a bytes pattern: `.` matches any
    // byte and \w/\s/\b are ASCII-only.
    RE.get_or_init(|| {
        ByteRegex::new(&format!("(?-u){AI_META_NAME_PATTERN}")).expect("static regex compiles")
    })
}

fn contains_subslice(haystack: &[u8], needle: &[u8]) -> bool {
    !needle.is_empty()
        && haystack
            .windows(needle.len())
            .any(|window| window == needle)
}

/// Scan a blob for C2PA and AI markers.
///
/// Returns `(has_c2pa, has_ai_metadata, findings)`, capped at 30 findings. A
/// marker already reported under `marker:` is not repeated under `ai:`.
pub fn blob_hits(blob: &[u8]) -> (bool, bool, Vec<String>) {
    let lower = blob.to_ascii_lowercase();
    let mut findings: Vec<String> = Vec::new();
    let mut has_c2pa = false;
    let mut has_ai = false;

    for needle in C2PA_MARKERS {
        if contains_subslice(&lower, &needle.to_ascii_lowercase()) {
            has_c2pa = true;
            findings.push(format!("marker:{}", String::from_utf8_lossy(needle)));
        }
    }
    for needle in AI_META_HINTS {
        if contains_subslice(&lower, &needle.to_ascii_lowercase()) {
            has_ai = true;
            let label = String::from_utf8_lossy(needle).into_owned();
            // The Python rebuilds this set each iteration from the labels
            // already recorded, so a marker reported once is not repeated.
            let already: Vec<&str> = findings
                .iter()
                .map(|finding| {
                    finding
                        .split_once(':')
                        .map(|(_, tail)| tail)
                        .unwrap_or(finding)
                })
                .collect();
            if !already.contains(&label.as_str()) {
                findings.push(format!("ai:{label}"));
            }
        }
    }
    findings.truncate(30);
    (has_c2pa, has_ai || has_c2pa, findings)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_clean_blob_finds_nothing() {
        let (c2pa, ai, findings) = blob_hits(b"an ordinary document body");
        assert!(!c2pa && !ai);
        assert!(findings.is_empty());
    }

    #[test]
    fn c2pa_markers_are_reported_once_under_the_marker_prefix() {
        let (c2pa, ai, findings) = blob_hits(b"...c2pa...");
        assert!(c2pa && ai);
        // Both table cases hit, and neither is repeated under `ai:`.
        assert_eq!(
            findings,
            vec!["marker:c2pa".to_string(), "marker:C2PA".to_string()]
        );
    }

    #[test]
    fn vendor_hints_are_reported_under_the_ai_prefix() {
        let (c2pa, ai, findings) = blob_hits(b"Generated by Anthropic");
        assert!(!c2pa);
        assert!(ai);
        assert_eq!(
            findings,
            vec!["ai:Generated by".to_string(), "ai:Anthropic".to_string()]
        );
    }

    #[test]
    fn findings_are_capped_at_thirty() {
        let mut blob = Vec::new();
        for needle in C2PA_MARKERS.iter().chain(AI_META_HINTS.iter()) {
            blob.extend_from_slice(needle);
            blob.push(b' ');
        }
        assert!(blob_hits(&blob).2.len() <= 30);
    }

    #[test]
    fn the_name_pattern_matches_provenance_words_case_insensitively() {
        let pattern = ai_meta_name_re();
        for name in ["generator", "AI-Generated", "digitalSourceType", "AIGC"] {
            assert!(pattern.is_match(name), "{name} should match");
        }
        assert!(!pattern.is_match("author"));
        assert!(!pattern.is_match("description"));
    }
}
