//! Byte patterns associated with C2PA / AI provenance.
//!
//! The tables carry both cases of several markers (`c2pa` and `C2PA`). Matching
//! is case-insensitive, so both entries hit and both are reported — the Python
//! did the same, and the duplicate is load-bearing for the finding strings
//! callers and tests match on.

/// Chunk types / content patterns associated with C2PA provenance.
pub const C2PA_MARKERS: &[&[u8]] = &[
    b"c2pa",
    b"C2PA",
    b"jumb",
    b"JUMB",
    b"c2ma",
    b"contentcredentials",
    b"contentauth",
    b"cai:",
    b"http://ns.adobe.com/xmp/InstanceID/", // not solely C2PA
];

/// Vendor and provenance markers that indicate AI metadata.
pub const AI_META_HINTS: &[&[u8]] = &[
    b"c2pa",
    b"C2PA",
    b"contentcredentials",
    b"ContentCredentials",
    b"digitalSourceType",
    b"trainedAlgorithmicMedia",
    b"compositeWithTrainedAlgorithmicMedia",
    b"algorithmicMedia",
    b"AIGC",
    b"aigc",
    b"AI generated",
    b"Generated by",
    b"Claude",
    b"Anthropic",
    b"OpenAI",
    b"SynthID",
    b"dcterms:provenance",
];

/// `AI_META_HINTS + C2PA_MARKERS`, the combined needle list the scanners use.
pub fn ai_and_c2pa_markers() -> Vec<&'static [u8]> {
    AI_META_HINTS
        .iter()
        .chain(C2PA_MARKERS.iter())
        .copied()
        .collect()
}

fn to_lower(data: &[u8]) -> Vec<u8> {
    data.to_ascii_lowercase()
}

fn contains_subslice(haystack: &[u8], needle: &[u8]) -> bool {
    if needle.is_empty() {
        return true;
    }
    haystack
        .windows(needle.len())
        .any(|window| window == needle)
}

/// Return every needle present in `blob`, case-insensitively, in table order.
pub fn contains_any(blob: &[u8], needles: &[&[u8]]) -> Vec<String> {
    let lower = to_lower(blob);
    needles
        .iter()
        .filter(|needle| contains_subslice(&lower, &to_lower(needle)))
        .map(|needle| String::from_utf8_lossy(needle).into_owned())
        .collect()
}

/// The `', '.join(hits[:n])` the finding strings use.
pub fn join_hits(hits: &[String], limit: usize) -> String {
    hits.iter()
        .take(limit)
        .cloned()
        .collect::<Vec<_>>()
        .join(", ")
}

/// True when any hit names a container-level C2PA structure.
pub fn hits_name_c2pa(hits: &[String], extra_contentauth: bool) -> bool {
    hits.iter().any(|hit| {
        let hit = hit.to_lowercase();
        hit == "c2pa"
            || hit == "contentcredentials"
            || hit == "jumb"
            || (extra_contentauth && hit == "contentauth")
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn matching_is_case_insensitive_and_reports_both_table_cases() {
        let hits = contains_any(b"...C2PA...", C2PA_MARKERS);
        assert_eq!(hits, vec!["c2pa".to_string(), "C2PA".to_string()]);
    }

    #[test]
    fn absent_markers_yield_nothing() {
        assert!(contains_any(b"an ordinary comment", C2PA_MARKERS).is_empty());
    }

    #[test]
    fn combined_table_keeps_hints_before_markers() {
        let combined = ai_and_c2pa_markers();
        assert_eq!(combined.len(), AI_META_HINTS.len() + C2PA_MARKERS.len());
        assert_eq!(combined[0], AI_META_HINTS[0]);
        assert_eq!(combined[AI_META_HINTS.len()], C2PA_MARKERS[0]);
    }

    #[test]
    fn join_hits_truncates_to_the_limit() {
        let hits: Vec<String> = (0..10).map(|i| format!("h{i}")).collect();
        assert_eq!(join_hits(&hits, 3), "h0, h1, h2");
    }

    #[test]
    fn c2pa_naming_recognises_the_container_markers() {
        assert!(hits_name_c2pa(&["jumb".into()], false));
        assert!(!hits_name_c2pa(&["contentauth".into()], false));
        assert!(hits_name_c2pa(&["contentauth".into()], true));
        assert!(!hits_name_c2pa(&["SynthID".into()], true));
    }
}
