//! Lossless-surgery guarantees, on real encoded images.
//!
//! These cover metrics 4 and 5 of the evaluation plan:
//!
//! 4. **Byte-exact round trip on untouched content.** A file with no provenance
//!    marks must come out byte-identical. Hashed before and after.
//! 5. **Image visual identity after a metadata strip.** Both sides are decoded
//!    and the pixel buffers compared for exact equality — not PSNR. If a single
//!    pixel changed, the tool re-encoded, and that is a bug.
//!
//! Every fixture is generated in-process, so the suite is hermetic: no checked
//! in binaries, and no `magick`, `exiftool` or `qpdf` on the test path.

use image::codecs::jpeg::JpegEncoder;
use image::codecs::png::PngEncoder;
use image::codecs::webp::WebPEncoder;
use image::{ExtendedColorType, ImageEncoder, ImageFormat, RgbaImage};
use img_parts::jpeg::{markers, Jpeg, JpegSegment};
use img_parts::png::{Png, PngChunk};
use img_parts::riff::{RiffChunk, RiffContent};
use img_parts::webp::WebP;
use img_parts::{Bytes, ImageEXIF};
use sha2::{Digest, Sha256};

use prose_sanitiser_media::image::{
    detect_format, inspect_bytes, jpeg::strip_jpeg, png::strip_png, webp::strip_webp,
};

const WIDTH: u32 = 24;
const HEIGHT: u32 = 16;

/// A deterministic, non-uniform image, so a re-encode would show up.
fn source_image() -> RgbaImage {
    RgbaImage::from_fn(WIDTH, HEIGHT, |x, y| {
        image::Rgba([
            (x * 9 % 256) as u8,
            (y * 15 % 256) as u8,
            ((x * y) % 256) as u8,
            255,
        ])
    })
}

fn clean_png() -> Vec<u8> {
    let source = source_image();
    let mut out = Vec::new();
    PngEncoder::new(&mut out)
        .write_image(source.as_raw(), WIDTH, HEIGHT, ExtendedColorType::Rgba8)
        .expect("the PNG fixture encodes");
    out
}

fn clean_jpeg() -> Vec<u8> {
    let source = image::DynamicImage::ImageRgba8(source_image()).to_rgb8();
    let mut out = Vec::new();
    JpegEncoder::new_with_quality(&mut out, 80)
        .write_image(source.as_raw(), WIDTH, HEIGHT, ExtendedColorType::Rgb8)
        .expect("the JPEG fixture encodes");
    out
}

fn clean_webp() -> Vec<u8> {
    let source = source_image();
    let mut out = Vec::new();
    WebPEncoder::new_lossless(&mut out)
        .write_image(source.as_raw(), WIDTH, HEIGHT, ExtendedColorType::Rgba8)
        .expect("the WebP fixture encodes");
    out
}

fn digest(data: &[u8]) -> [u8; 32] {
    Sha256::digest(data).into()
}

/// A JUMBF APP11 packet with the JPEG XT part 3 header.
fn app11_packet(instance: u16, sequence: u32, payload: &[u8]) -> Bytes {
    let mut out = b"JP".to_vec();
    out.extend_from_slice(&instance.to_be_bytes());
    out.extend_from_slice(&sequence.to_be_bytes());
    out.extend_from_slice(payload);
    Bytes::from(out)
}

/// The JUMBF type UUID a C2PA manifest store declares (C2PA 2.4).
const C2PA_JUMBF_UUID: [u8; 16] = [
    0x63, 0x32, 0x70, 0x61, 0x00, 0x11, 0x00, 0x10, 0x80, 0x00, 0x00, 0xAA, 0x00, 0x38, 0x9B, 0x71,
];

fn iso_box(tbox: &[u8; 4], payload: &[u8]) -> Vec<u8> {
    let mut out = ((payload.len() + 8) as u32).to_be_bytes().to_vec();
    out.extend_from_slice(tbox);
    out.extend_from_slice(payload);
    out
}

/// A genuine C2PA JUMBF superbox: `jumb` wrapping a `jumd` description box with
/// the C2PA type UUID and the `c2pa` label. Anything less is not a manifest
/// store, and the scanners are now entitled to say so.
fn c2pa_jumbf(content: &[u8]) -> Vec<u8> {
    let mut description = C2PA_JUMBF_UUID.to_vec();
    description.push(0x02); // toggles: a label follows
    description.extend_from_slice(b"c2pa\0");
    let mut body = iso_box(b"jumd", &description);
    body.extend_from_slice(&iso_box(b"c2cl", content));
    iso_box(b"jumb", &body)
}

/// The clean PNG plus an `eXIf` chunk, an XMP `iTXt`, a vendor `tEXt` and a
/// `caBX` JUMBF box.
fn marked_png() -> Vec<u8> {
    let mut png = Png::from_bytes(Bytes::from(clean_png())).expect("the fixture parses");
    let end = png.chunks().len() - 1; // insert ahead of IEND
    let mut xmp = b"XML:com.adobe.xmp\0\0\0\0\0".to_vec();
    xmp.extend_from_slice(br#"<x:xmpmeta><rdf:RDF>digitalSourceType</rdf:RDF></x:xmpmeta>"#);
    for chunk in [
        PngChunk::new(*b"eXIf", Bytes::from_static(b"II*\0\x08\0\0\0")),
        PngChunk::new(*b"iTXt", Bytes::from(xmp)),
        PngChunk::new(
            *b"tEXt",
            Bytes::from_static(b"Software\0Generated by Claude"),
        ),
        PngChunk::new(*b"caBX", Bytes::from(c2pa_jumbf(b"manifest"))),
    ] {
        png.chunks_mut().insert(end, chunk);
    }
    png.encoder().bytes().to_vec()
}

/// The clean JPEG plus an Exif APP1, an XMP APP1 and a two-packet APP11 JUMBF
/// box whose marker straddles the segment boundary.
fn marked_jpeg() -> Vec<u8> {
    let mut jpeg = Jpeg::from_bytes(Bytes::from(clean_jpeg())).expect("the fixture parses");
    let segments = vec![
        JpegSegment::new_with_contents(
            markers::APP1,
            Bytes::from_static(b"Exif\0\0II*\0\x08\0\0\0"),
        ),
        JpegSegment::new_with_contents(
            markers::APP1,
            Bytes::from_static(
                b"http://ns.adobe.com/xap/1.0/\0<x:xmpmeta>trainedAlgorithmicMedia</x:xmpmeta>",
            ),
        ),
        JpegSegment::new_with_contents(markers::APP11, app11_packet(1, 0, &c2pa_jumbf(b"claim"))),
        JpegSegment::new_with_contents(markers::APP11, app11_packet(1, 1, b"credentials tail")),
        JpegSegment::new_with_contents(markers::COM, Bytes::from_static(b"made with OpenAI")),
    ];
    for (offset, segment) in segments.into_iter().enumerate() {
        jpeg.segments_mut().insert(1 + offset, segment);
    }
    jpeg.encoder().bytes().to_vec()
}

/// The clean WebP promoted to VP8X with `EXIF`, `XMP ` and `C2PA` chunks.
fn marked_webp() -> Vec<u8> {
    let mut webp = WebP::from_bytes(Bytes::from(clean_webp())).expect("the fixture parses");
    webp.set_exif(Some(Bytes::from_static(b"II*\0\x08\0\0\0")));
    webp.chunks_mut().push(RiffChunk::new(
        *b"XMP ",
        RiffContent::Data(Bytes::from_static(
            b"<x:xmpmeta>digitalSourceType</x:xmpmeta>",
        )),
    ));
    webp.chunks_mut().push(RiffChunk::new(
        *b"C2PA",
        RiffContent::Data(Bytes::from_static(b"jumb c2pa manifest store")),
    ));
    webp.encoder().bytes().to_vec()
}

type Strip = fn(&[u8], bool) -> Result<(Vec<u8>, Vec<String>), String>;

/// One format under test: a clean fixture, a marked one, and how to strip it.
struct Case {
    format: &'static str,
    clean: Vec<u8>,
    marked: Vec<u8>,
    strip: Strip,
    image_format: ImageFormat,
}

fn cases() -> Vec<Case> {
    vec![
        Case {
            format: "png",
            clean: clean_png(),
            marked: marked_png(),
            strip: strip_png,
            image_format: ImageFormat::Png,
        },
        Case {
            format: "jpeg",
            clean: clean_jpeg(),
            marked: marked_jpeg(),
            strip: strip_jpeg,
            image_format: ImageFormat::Jpeg,
        },
        Case {
            format: "webp",
            clean: clean_webp(),
            marked: marked_webp(),
            strip: strip_webp,
            image_format: ImageFormat::WebP,
        },
    ]
}

#[test]
fn the_fixtures_are_what_they_claim_to_be() {
    for case in cases() {
        let format = case.format;
        assert_eq!(detect_format(&case.clean), format);
        assert_eq!(detect_format(&case.marked), format);

        let (_, c2pa, ai, findings) = inspect_bytes(&case.marked);
        assert!(c2pa, "{format} fixture must carry a C2PA marker");
        assert!(ai, "{format} fixture must carry AI metadata");
        assert!(!findings.is_empty());

        let (_, c2pa, ai, findings) = inspect_bytes(&case.clean);
        assert!(
            !c2pa && !ai,
            "{format} clean fixture is not clean: {findings:?}"
        );
    }
}

/// Metric 4: a file with no provenance marks comes out byte-identical.
#[test]
fn a_clean_file_survives_a_strip_byte_for_byte() {
    for case in cases() {
        let format = case.format;
        let before = digest(&case.clean);
        let (after, actions) = (case.strip)(&case.clean, true).expect("a clean file strips");
        assert_eq!(
            digest(&after),
            before,
            "{format} was rewritten despite carrying no marks"
        );
        assert_eq!(
            actions.len(),
            1,
            "{format} should report exactly one no-op action, got {actions:?}"
        );
    }
}

/// Metric 5: the pixel buffer is identical after a strip, exactly.
#[test]
fn stripping_metadata_leaves_the_pixels_untouched() {
    for case in cases() {
        let format = case.format;
        let (cleaned, actions) = (case.strip)(&case.marked, true).expect("a marked file strips");
        assert!(
            cleaned.len() < case.marked.len(),
            "{format} should have lost bytes; actions were {actions:?}"
        );

        let before = image::load_from_memory_with_format(&case.marked, case.image_format)
            .unwrap_or_else(|error| panic!("{format} before: {error}"))
            .to_rgba8();
        let after = image::load_from_memory_with_format(&cleaned, case.image_format)
            .unwrap_or_else(|error| panic!("{format} after: {error}"))
            .to_rgba8();

        assert_eq!(before.dimensions(), after.dimensions(), "{format} resized");
        assert_eq!(
            before.as_raw(),
            after.as_raw(),
            "{format} pixels changed: the container surgery re-encoded the image"
        );
    }
}

#[test]
fn stripping_metadata_removes_every_marker() {
    for case in cases() {
        let format = case.format;
        let (cleaned, _) = (case.strip)(&case.marked, true).expect("a marked file strips");
        let (_, c2pa, ai, findings) = inspect_bytes(&cleaned);
        assert!(!c2pa, "{format} still reports C2PA: {findings:?}");
        assert!(!ai, "{format} still reports AI metadata: {findings:?}");
    }
}

#[test]
fn a_strip_is_idempotent() {
    for case in cases() {
        let format = case.format;
        let (once, _) = (case.strip)(&case.marked, true).expect("a marked file strips");
        let (twice, actions) = (case.strip)(&once, true).expect("a cleaned file strips");
        assert_eq!(once, twice, "{format} changed on a second pass");
        assert_eq!(
            actions.len(),
            1,
            "{format} found something to remove twice: {actions:?}"
        );
    }
}

/// The compressed image data itself is carried across verbatim, which is a
/// stronger statement than pixel equality: it rules out a decode and re-encode
/// that happened to be lossless.
#[test]
fn the_compressed_image_data_is_carried_across_verbatim() {
    let marked = marked_png();
    let (cleaned, _) = strip_png(&marked, true).unwrap();
    let idat_of = |data: &[u8]| -> Vec<u8> {
        Png::from_bytes(Bytes::from(data.to_vec()))
            .unwrap()
            .chunks()
            .iter()
            .filter(|chunk| chunk.kind() == *b"IDAT")
            .flat_map(|chunk| chunk.contents().to_vec())
            .collect()
    };
    assert_eq!(idat_of(&marked), idat_of(&cleaned));

    let marked = marked_jpeg();
    let (cleaned, _) = strip_jpeg(&marked, true).unwrap();
    let scan_of = |data: &[u8]| -> Vec<u8> {
        let jpeg = Jpeg::from_bytes(Bytes::from(data.to_vec())).unwrap();
        jpeg.segments()
            .iter()
            .find(|segment| segment.marker() == markers::SOS)
            .expect("the fixture has a scan")
            .contents()
            .to_vec()
    };
    assert_eq!(scan_of(&marked), scan_of(&cleaned));
}
