use super::*;

use lopdf::{dictionary, IncrementalDocument, Stream};

/// A hand-assembled byte blob shaped like a PDF, for the marker-scan tests.
///
/// Deliberately not a parseable document: it exercises the byte-level fallback
/// that runs when `lopdf` cannot load the file.
fn pdf_blob(objects: &[u8], stream_payload: &[u8]) -> Vec<u8> {
    let mut out = b"%PDF-1.7\n".to_vec();
    out.extend_from_slice(objects);
    out.extend_from_slice(b"\n4 0 obj\nstream\n");
    out.extend_from_slice(stream_payload);
    out.extend_from_slice(b"\nendstream\nendobj\n%%EOF\n");
    out
}

const XMP: &[u8] = br#"<?xpacket begin='' id='W5M0MpCehiHzreSzNTczkc9d'?>
<x:xmpmeta xmlns:x="adobe:ns:meta/"><rdf:RDF><rdf:Description
 xmp:CreatorTool="Generated by Claude" /></rdf:RDF></x:xmpmeta>
<?xpacket end='w'?>"#;

/// A real, parseable one-page PDF carrying an `/Info` dictionary and an XMP
/// `/Metadata` stream.
fn real_pdf(author: &str) -> Vec<u8> {
    let mut doc = Document::with_version("1.7");
    let pages_id = doc.new_object_id();
    let page_id = doc.add_object(dictionary! {
        "Type" => "Page",
        "Parent" => pages_id,
        "MediaBox" => vec![0.into(), 0.into(), 200.into(), 200.into()],
    });
    doc.set_object(
        pages_id,
        dictionary! {
            "Type" => "Pages",
            "Kids" => vec![page_id.into()],
            "Count" => 1,
        },
    );
    let metadata_id = doc.add_object(Stream::new(
        dictionary! { "Type" => "Metadata", "Subtype" => "XML" },
        XMP.to_vec(),
    ));
    let catalog_id = doc.add_object(dictionary! {
        "Type" => "Catalog",
        "Pages" => pages_id,
        "Metadata" => metadata_id,
    });
    let info_id = doc.add_object(dictionary! {
        "Author" => Object::string_literal(author),
        "Producer" => Object::string_literal("Generated by Claude"),
        "CreationDate" => Object::string_literal("D:20260903120000Z"),
    });
    doc.trailer.set("Root", catalog_id);
    doc.trailer.set("Info", info_id);

    let mut out = Vec::new();
    doc.save_to(&mut out).expect("the fixture serialises");
    out
}

/// The same document with a second author written as an *incremental update*,
/// so the first author's bytes are still present earlier in the file.
fn pdf_with_incremental_metadata(first: &str, second: &str) -> Vec<u8> {
    let base = real_pdf(first);
    let parsed = Document::load_mem(&base).expect("the fixture parses");
    let info_id = parsed
        .trailer
        .get(b"Info")
        .and_then(Object::as_reference)
        .expect("the fixture has an /Info reference");

    let mut incremental = IncrementalDocument::create_from(base.clone(), parsed);
    incremental.new_document.set_object(
        info_id,
        dictionary! {
            "Author" => Object::string_literal(second),
            "Producer" => Object::string_literal("Generated by Claude"),
        },
    );
    let mut out = Vec::new();
    incremental
        .save_to(&mut out)
        .expect("the incremental update serialises");

    assert!(
        contains(&out, first.as_bytes()),
        "the fixture must keep the superseded revision in the byte stream"
    );
    assert!(contains(&out, second.as_bytes()));
    out
}

fn contains(haystack: &[u8], needle: &[u8]) -> bool {
    haystack
        .windows(needle.len())
        .any(|window| window == needle)
}

#[test]
fn stream_payloads_are_excluded_from_the_marker_scan() {
    // "AIGC" occurs only inside compressed stream bytes: a chance collision.
    let pdf = pdf_blob(b"1 0 obj<</Title(Hills)>>endobj", b"\x9c\x00AIGC\x01\xff");
    let blob = pdf_structured_blob(&pdf);
    assert!(!contains(&blob, b"AIGC"));
    assert!(contains(&blob, b"Hills"));
}

#[test]
fn dictionary_markers_are_still_found() {
    let pdf = pdf_blob(
        b"1 0 obj<</Producer(Generated by OpenAI)>>endobj",
        b"binary",
    );
    let blob = pdf_structured_blob(&pdf);
    let (_, ai, hits) = blob_hits(&blob);
    assert!(ai);
    assert!(hits.iter().any(|hit| hit == "ai:OpenAI"));
}

#[test]
fn xmp_packets_are_kept_in_the_scanned_blob() {
    let mut pdf = pdf_blob(b"1 0 obj<<>>endobj", b"stream-bytes");
    pdf.extend_from_slice(
        b"<?xpacket begin='' id='W5M0'?><x>digitalSourceType</x><?xpacket end='w'?>",
    );
    let blob = pdf_structured_blob(&pdf);
    assert!(contains(&blob, b"digitalSourceType"));
}

#[test]
fn inspect_reports_an_xmp_packet_and_sets_the_ai_flag() {
    let dir = tempfile::tempdir().unwrap();
    let path = dir.path().join("doc.pdf");
    let mut pdf = pdf_blob(b"1 0 obj<<>>endobj", b"bytes");
    pdf.extend_from_slice(
        b"<?xpacket begin='' id='W5M0'?><x>trainedAlgorithmicMedia</x><?xpacket end='w'?>",
    );
    std::fs::write(&path, &pdf).unwrap();

    let (_, ai, findings, details) = inspect_pdf(&path, &pdf);
    assert!(ai);
    assert!(findings.contains(&"XMP packet present".to_string()));
    assert!(details["tools"]["exiftool"]["available"].is_boolean());
}

#[test]
fn inspect_reports_the_object_graph_when_the_document_parses() {
    let dir = tempfile::tempdir().unwrap();
    let path = dir.path().join("real.pdf");
    let pdf = real_pdf("Ada Lovelace");
    std::fs::write(&path, &pdf).unwrap();

    let (_, ai, findings, details) = inspect_pdf(&path, &pdf);
    assert!(ai, "the XMP names a vendor");
    assert_eq!(details["structure"]["parsed"], serde_json::json!(true));
    assert_eq!(
        details["structure"]["metadata_streams"],
        serde_json::json!(1)
    );
    assert!(
        findings.iter().any(|f| f.starts_with("PDF /Info keys: ")),
        "findings were {findings:?}"
    );
    assert!(findings.contains(&"PDF /Metadata streams: 1".to_string()));
}

#[test]
fn a_clean_pdf_reports_nothing_structural() {
    let dir = tempfile::tempdir().unwrap();
    let path = dir.path().join("clean.pdf");
    let pdf = pdf_blob(b"1 0 obj<</Title(Hills)>>endobj", b"image-bytes");
    std::fs::write(&path, &pdf).unwrap();
    let (c2pa, ai, findings, _) = inspect_pdf(&path, &pdf);
    assert!(!c2pa && !ai, "findings were {findings:?}");
}

#[test]
fn an_unparseable_pdf_fails_closed_and_writes_nothing() {
    // Replaces the old "always produces an output file and a mode" test. A
    // degraded result is not a clean: a byte-level edit cannot reach /Info and
    // leaves /Length values and cross-reference offsets pointing at the wrong
    // places, and a straight copy retains everything. Both used to return Ok.
    let dir = tempfile::tempdir().unwrap();
    let source = dir.path().join("in.pdf");
    let dest = dir.path().join("out.pdf");
    let pdf = pdf_blob(b"1 0 obj<</Producer(Generated by OpenAI)>>endobj", b"bytes");
    std::fs::write(&source, &pdf).unwrap();

    let error = clean_pdf(&source, &dest).unwrap_err();
    assert!(
        error.contains("cannot build a complete object graph"),
        "error was {error}"
    );
    assert!(error.contains("nothing was written"));
    assert!(!dest.exists(), "no destination may be created on failure");
}

#[test]
fn an_unparseable_pdf_with_an_xmp_packet_is_refused_rather_than_regex_edited() {
    let dir = tempfile::tempdir().unwrap();
    let source = dir.path().join("in.pdf");
    let dest = dir.path().join("out.pdf");
    let mut pdf = pdf_blob(b"1 0 obj<< /Length 123 /Type /Metadata >>endobj", b"bytes");
    pdf.extend_from_slice(XMP);
    std::fs::write(&source, &pdf).unwrap();

    assert!(clean_pdf(&source, &dest).is_err());
    assert!(!dest.exists());
}

#[test]
fn a_parseable_pdf_takes_the_object_graph_rewrite() {
    let dir = tempfile::tempdir().unwrap();
    let source = dir.path().join("in.pdf");
    let dest = dir.path().join("out.pdf");
    std::fs::write(&source, real_pdf("Ada Lovelace")).unwrap();

    let (actions, meta) = clean_pdf(&source, &dest).unwrap();
    assert_eq!(meta["mode"], serde_json::json!("lopdf"));
    assert_eq!(meta["structural_rewrite"], serde_json::json!(true));
    assert_eq!(meta["verified"], serde_json::json!(true));
    assert!(actions.contains(&"remove trailer /Info".to_string()));
    assert!(actions.contains(&"remove catalog /Metadata".to_string()));

    let cleaned = std::fs::read(&dest).unwrap();
    assert!(!contains(&cleaned, b"Ada Lovelace"));
    assert!(!contains(&cleaned, b"Generated by Claude"));
    assert!(!contains(&cleaned, b"xpacket"));
    // Still a document: it reloads and keeps its single page.
    let reloaded = Document::load_mem(&cleaned).expect("the output is a valid PDF");
    assert_eq!(reloaded.get_pages().len(), 1);
    assert!(reloaded.trailer.get(b"Info").is_err());
}

#[test]
fn an_incremental_update_cannot_resurrect_the_superseded_metadata() {
    let dir = tempfile::tempdir().unwrap();
    let source = dir.path().join("incremental.pdf");
    let dest = dir.path().join("out.pdf");
    let pdf = pdf_with_incremental_metadata("Ada Lovelace", "Claude");
    std::fs::write(&source, &pdf).unwrap();

    let (_, meta) = clean_pdf(&source, &dest).unwrap();
    assert_eq!(meta["structural_rewrite"], serde_json::json!(true));

    let cleaned = std::fs::read(&dest).unwrap();
    // Neither revision's author survives anywhere in the output byte stream.
    assert!(
        !contains(&cleaned, b"Ada Lovelace"),
        "the superseded /Info must not survive the rewrite"
    );
    assert!(!contains(&cleaned, b"Claude"));
    assert!(!contains(&cleaned, b"xpacket"));
    assert_eq!(
        Document::load_mem(&cleaned)
            .expect("the output is a valid PDF")
            .get_pages()
            .len(),
        1
    );
}

/// A PDF carrying its C2PA manifest the way the specification says: an embedded
/// file specification with `/AFRelationship /C2PA_Manifest`, referenced from the
/// catalogue's `/AF` array.
fn pdf_with_c2pa_embedded_file() -> Vec<u8> {
    let mut doc = Document::with_version("1.7");
    let pages_id = doc.new_object_id();
    let page_id = doc.add_object(dictionary! {
        "Type" => "Page",
        "Parent" => pages_id,
        "MediaBox" => vec![0.into(), 0.into(), 200.into(), 200.into()],
    });
    doc.set_object(
        pages_id,
        dictionary! { "Type" => "Pages", "Kids" => vec![page_id.into()], "Count" => 1 },
    );
    let manifest_id = doc.add_object(Stream::new(
        dictionary! { "Type" => "EmbeddedFile" },
        b"jumb c2pa manifest store".to_vec(),
    ));
    let spec_id = doc.add_object(dictionary! {
        "Type" => "Filespec",
        "F" => Object::string_literal("c2pa.c2pa"),
        "AFRelationship" => "C2PA_Manifest",
        "EF" => dictionary! { "F" => manifest_id },
    });
    let catalog_id = doc.add_object(dictionary! {
        "Type" => "Catalog",
        "Pages" => pages_id,
        "AF" => vec![spec_id.into()],
    });
    doc.trailer.set("Root", catalog_id);

    let mut out = Vec::new();
    doc.save_to(&mut out).expect("the fixture serialises");
    out
}

#[test]
fn a_c2pa_embedded_file_specification_is_removed_with_its_stream() {
    let dir = tempfile::tempdir().unwrap();
    let source = dir.path().join("c2pa.pdf");
    let dest = dir.path().join("out.pdf");
    let pdf = pdf_with_c2pa_embedded_file();
    assert!(contains(&pdf, b"C2PA_Manifest"));
    std::fs::write(&source, &pdf).unwrap();

    let (actions, _) = clean_pdf(&source, &dest).unwrap();
    assert!(
        actions
            .iter()
            .any(|a| a.starts_with("drop C2PA embedded-file specification")),
        "actions were {actions:?}"
    );
    let cleaned = std::fs::read(&dest).unwrap();
    assert!(!contains(&cleaned, b"C2PA_Manifest"));
    assert!(!contains(&cleaned, b"jumb c2pa manifest store"));
    assert_eq!(
        Document::load_mem(&cleaned)
            .expect("the output is a valid PDF")
            .get_pages()
            .len(),
        1
    );
}

#[test]
fn every_written_output_has_been_verified() {
    let dir = tempfile::tempdir().unwrap();
    let source = dir.path().join("in.pdf");
    let dest = dir.path().join("out.pdf");
    std::fs::write(&source, real_pdf("Ada Lovelace")).unwrap();

    let (actions, _) = clean_pdf(&source, &dest).unwrap();
    assert!(actions
        .iter()
        .any(|a| a.starts_with("verified: the output reparses")));

    // The verification is a real gate, not a label: it rejects a document that
    // still carries a metadata carrier.
    let mut doc = Document::load_mem(&real_pdf("Ada Lovelace")).unwrap();
    let mut untouched = Vec::new();
    doc.save_to(&mut untouched).unwrap();
    assert!(verify(&untouched).is_err(), "an unscrubbed PDF must fail");
}
